version: 2

sources:
  - name: northwind
    database: northwind
    schema: northwind
    tables: 
      - name: categories
      - name: products
      - name: suppliers
      - name: orders
      - name: order_details