northwind:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: '{{ env_var("SNOWFLAKE_ACCOUNT") }}'

      # User/password auth
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: accountadmin
      database: northwind
      warehouse: xsmall_wh
      schema: northwind
      threads: 12
      client_session_keep_alive: False